In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("/Users/chuamelia/Desktop/nycaasc/research/data/fb/2016_spring_page_level_.csv")

In [4]:
data.head()

,﻿Date,Lifetime Total Likes,Daily New Likes,Daily Unlikes,Daily Page Engaged Users,Weekly Page Engaged Users,28 Days Page Engaged Users,Daily Like Sources - API,Daily Like Sources - Ads,Daily Like Sources - On Your Page,...,page_cta_clicks_by_age_gender_logged_in_unique:week - 55-64.U,page_cta_clicks_by_age_gender_logged_in_unique:week - 65+.F,page_cta_clicks_by_age_gender_logged_in_unique:week - 65+.M,page_cta_clicks_by_age_gender_logged_in_unique:week - 65+.U,page_cta_clicks_by_age_gender_logged_in_unique:week - &lt;13.F,page_cta_clicks_by_age_gender_logged_in_unique:week - &lt;13.M,page_cta_clicks_by_age_gender_logged_in_unique:week - &lt;13.U,page_cta_clicks_by_age_gender_logged_in_unique:week - UNKNOWN.F,page_cta_clicks_by_age_gender_logged_in_unique:week - UNKNOWN.M,page_cta_clicks_by_age_gender_logged_in_unique:week - UNKNOWN.U
0,NaN,Lifetime: The total number of people who have ...,Daily: The number of new people who have liked...,Daily: The number of Unlikes of your Page (Uni...,Daily: The number of people who engaged with y...,Weekly: The number of people who engaged with ...,28 Days: The number of people who engaged with...,Daily: The number of people who liked your Pag...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-01,1070,0,0,0,16,64,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-02,1070,0,0,2,13,63,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2016-01-03,1070,0,0,2,13,60,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2016-01-04,1071,1,0,1,12,61,NaN,NaN,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0